services:
  - type: web
    name: workout-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    rootDir: backend
    plan: free
    envVars:
      - key: RENDER_PYTHON_PACKAGE_MANAGER
        value: pip